databases:
  - name: spacer
    databaseName: spacer
    user: spacer_user

services:
  - type: web
    name: leisure
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: leisure
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
